repos:
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "--rcfile=dependencies/app.pylintrc",
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--fail-under=7"
        ]